version: '3'

services:
  app:
    build: ./frontend
    ports:
      - 3001:3000
    volumes:
      - /usr/src/app
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - 3000:3000
    volumes:
      - /home/src/backend